# Generated by Django 5.0.1 on 2024-01-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id_dispositivo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('localizacion', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('sistema_operativo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Red',
            fields=[
                ('id_red', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('ip', models.CharField(max_length=20)),
                ('mascara', models.CharField(max_length=20)),
                ('puerta_enlace', models.CharField(max_length=20)),
                ('dispositivos', models.ManyToManyField(to='ponte.dispositivo')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id_grupo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('redes', models.ManyToManyField(to='ponte.red')),
            ],
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='servicios',
            field=models.ManyToManyField(to='ponte.servicio'),
        ),
    ]
