# Generated by Django 5.0.1 on 2024-01-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponte', '0003_red_latitud_red_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='red',
            name='tipo',
            field=models.CharField(choices=[('Educativa', 'Educativa'), ('Personal', 'Personal'), ('Empresarial', 'Empresarial')], max_length=20),
        ),
    ]
