# Generated by Django 5.0.1 on 2024-02-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponte', '0005_dispositivo_ip_privada'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='puerto',
            field=models.CharField(default='33', max_length=20),
            preserve_default=False,
        ),
    ]
