# Generated by Django 5.0.1 on 2024-02-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponte', '0007_dispositivo_mac'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ancla',
            fields=[
                ('id_ancla', models.AutoField(primary_key=True, serialize=False)),
                ('ip_publica', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('latitud', models.CharField(max_length=20)),
                ('longitud', models.CharField(max_length=20)),
            ],
        ),
    ]
