# Generated by Django 5.0.1 on 2024-02-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponte', '0010_alter_ancla_estado_alter_dispositivo_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='servicios',
            field=models.ManyToManyField(blank=True, to='ponte.servicio'),
        ),
    ]
