# Generated by Django 5.0.1 on 2024-02-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponte', '0011_alter_dispositivo_servicios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ancla',
            name='estado',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='estado',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='estado',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='red',
            name='estado',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.BooleanField(blank=True),
        ),
    ]
