# Generated by Django 5.0.1 on 2024-02-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponte', '0012_alter_ancla_estado_alter_dispositivo_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='ancla',
            name='tipo',
            field=models.CharField(choices=[('Educativa', 'Educativa'), ('Personal', 'Personal'), ('Empresarial', 'Empresarial')], max_length=20),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='tipo',
            field=models.CharField(choices=[('Educativa', 'Educativa'), ('Personal', 'Personal'), ('Empresarial', 'Empresarial')], max_length=20),
        ),
    ]
