# Generated by Django 5.0.1 on 2024-02-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponte', '0014_alter_ancla_estado_alter_red_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anchor',
            fields=[
                ('anchor_id', models.AutoField(primary_key=True, serialize=False)),
                ('public_ip', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('Educational', 'Educational'), ('Personal', 'Personal'), ('Business', 'Business')], max_length=20)),
                ('status', models.BooleanField()),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('status', models.BooleanField(blank=True)),
                ('operating_system', models.CharField(max_length=20)),
                ('private_ip', models.CharField(max_length=20)),
                ('mac_address', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('Educational', 'Educational'), ('Personal', 'Personal'), ('Business', 'Business')], max_length=20)),
                ('state', models.BooleanField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('network_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('Educational', 'Educational'), ('Personal', 'Personal'), ('Business', 'Business')], max_length=20)),
                ('status', models.BooleanField()),
                ('ip', models.CharField(max_length=20)),
                ('subnet_mask', models.CharField(max_length=20)),
                ('gateway', models.CharField(max_length=20)),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('devices', models.ManyToManyField(to='ponte.device')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('status', models.BooleanField(blank=True)),
                ('port', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Ancla',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='servicios',
        ),
        migrations.RemoveField(
            model_name='red',
            name='dispositivos',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='redes',
        ),
        migrations.AddField(
            model_name='group',
            name='networks',
            field=models.ManyToManyField(to='ponte.network'),
        ),
        migrations.AddField(
            model_name='device',
            name='services',
            field=models.ManyToManyField(blank=True, to='ponte.service'),
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
        migrations.DeleteModel(
            name='Dispositivo',
        ),
        migrations.DeleteModel(
            name='Grupo',
        ),
        migrations.DeleteModel(
            name='Red',
        ),
    ]
